version: '2.15'

networks:
  foodshed-net:
    driver: bridge

services:
  foodshed-postgres:
    image: postgres
    environment:
      POSTGRES_USER: foodshed
      POSTGRES_PASSWORD: foodshed
      POSTGRES_DB: foodshed
      POSTGRES_HOST: foodshed-postgres

  foodshed:
    build: .
    image: foodshed:0.1
    ports:
        - 8000:8000
    tty: true
    restart:
        always
#     command: python -m gunicorn CapstoneProject.asgi:application -k uvicorn.workers.UvicornWorker
# Don't use this yet, it's for deployment only. In the docker terminal just run 'python manage.py runserver 0.0.0.0:8000' when you are developing. Run migrations too.
# A script needs to be created when it connects to the db. (Carlos)
