version: '2.15'

networks:
  foodshed-net:
    driver: bridge

services:
  foodshed-postgres:
    image: postgres
    environment:
      POSTGRES_USER: foodshed
      POSTGRES_PASSWORD: foodshed
      POSTGRES_DB: foodshed
      POSTGRES_HOST: foodshed-postgres

  foodshed:
    build: .
    image: foodshed:0.1
    ports:
        - 8000:8000
    tty: true
    restart:
        always
    command: python -m gunicorn CapstoneProject.asgi:application -k uvicorn.workers.UvicornWorker